export const SERVICE_STRINGS = {
  requestFailed: 'The portal could not complete that request. Try again.',
  permissionDenied: 'You do not have permission to complete this action.',
  recordNotFound: 'The requested portal record was not found.',
  recordConflict: 'This record changed since it was loaded. Refresh and try again.',
  timeout: 'The request took too long. Try again.',
  profileLoad: 'Your Microsoft 365 profile could not be loaded.',
  otherProfileLoad: 'This Microsoft 365 profile could not be loaded.',
  peopleSearch: 'People search is not available right now.',
  groupLoad: 'Community group details could not be loaded.',
  membershipCheck: 'Community membership could not be checked.',
  membershipDisabled: 'Online joining is not enabled yet. Open the Viva Engage community link to request access.',
  joinFailed: 'You could not be added to this community.',
  permissionsLoad: 'Your portal permissions could not be resolved.',
  directoryLoad: 'The community directory could not be loaded.',
  communityLoad: 'The community could not be loaded.',
  detailLoad: 'Community details could not be loaded.',
  rolesLoad: 'Community roles could not be loaded.',
  charterLoad: 'The community charter could not be loaded.',
  ipCatalogLoad: 'The IP catalog could not be loaded.',
  metricsLoad: 'Health metrics could not be loaded.',
  retirementLoad: 'The retirement register could not be loaded.',
  charterSave: 'The charter could not be saved.',
  duplicateCharter: 'A charter already exists for this community.',
  charterMustStartDraft: 'A new charter must start in Draft.',
  charterReadOnly: 'Signed-off charters are read-only.',
  charterTransition: (from: string, to: string): string => `A charter cannot move from ${from} to ${to}.`,
  charterReload: 'The charter was saved but could not be reloaded.',
  charterMissing: 'No charter exists for this community.',
  roleSave: 'The community role could not be saved.',
  roleReload: 'The role was saved but could not be reloaded.',
  metricSave: 'The health metric could not be saved.',
  metricNumeric: 'Enter a numeric metric value.',
  baselineExists: 'A baseline already exists for this community and measure.',
  metricReload: 'The metric was saved but could not be reloaded.',
  retirementSave: 'The retirement item could not be saved.',
  retirementRequired: 'Forum name and target community are required.',
  retirementReload: 'The retirement item was saved but could not be reloaded.',
  addedIdMissing: 'SharePoint did not return an ID for the saved item.',
  provisioningFailed: 'Portal lists could not be provisioned.',
  selectCommunity: 'Select a community.',
  readinessRequired: 'Complete all six launch-readiness checks before sign-off.',
  signOffsRequired: 'Community Lead, Program Manager, and Subject Matter Expert sign-offs and dates are required.'
} as const;