define([], function () {
  return {
    LoadingLabel: 'Loading portal data',
    RetryLabel: 'Try again',
    RequestFailedMessage: 'The portal could not complete that request.',
    JoinFailedMessage: 'The join request could not be completed.',
    CharterActionFailedMessage: 'The charter action could not be completed.',
    RetirementSaveFailedMessage: 'The retirement item could not be saved.',
    AccessDeniedTitle: 'This view is restricted',
    AccessDeniedMessage: 'Your SharePoint permissions do not include this governance view.',
    EmptyValue: 'Not recorded',
    SaveLabel: 'Save',
    CancelLabel: 'Cancel',
    EditLabel: 'Edit',
    DirectoryTitle: 'Technical communities',
    DirectorySubtitle: 'Find the community aligned to your work, scope, and role.',
    SearchPlaceholder: 'Search communities or scope',
    FamilyFilterLabel: 'Service family',
    RoleFilterLabel: 'Target role',
    StatusFilterLabel: 'Status',
    AllFamiliesLabel: 'All service families',
    AllRolesLabel: 'All target roles',
    AllStatusesLabel: 'All statuses',
    ViewCommunityLabel: 'View community',
    CrossCommunityLabel: 'Cross-community',
    InScopeLabel: 'In scope',
    OutOfScopeLabel: 'Out of scope',
    NoCommunitiesTitle: 'No communities match',
    NoCommunitiesMessage: 'Clear or change the filters to see more communities.',
    DetailSubtitle: 'Scope, people, reusable IP, and community channels.',
    RolesTitle: 'Community roles',
    IpCatalogTitle: 'Owned IP',
    ChannelsTitle: 'Community channels',
    VivaEngageLabel: 'Open Viva Engage',
    ChatLabel: 'Open support chat',
    JoinLabel: 'Join community',
    JoinedLabel: 'You are a member',
    JoinUnavailableLabel: 'Request access in Viva Engage',
    NoRolesLabel: 'No active role holders are recorded.',
    NoIpLabel: 'No offerings are currently aligned.',
    CrossTrainingNoIpLabel: 'No offerings aligned. The community exists to improve Delivery Excellence.',
    AiNoIpLabel: 'No offerings aligned. The community exists to build internal AI readiness and responsible adoption.',
    SecondJoinTitle: 'Join another community?',
    SecondJoinMessage: 'You already belong to another technical community. Confirm that you want to join this one as well.',
    ConfirmJoinLabel: 'Join this community',
    MyCommunityTitle: 'My communities',
    MyCommunitySubtitle: 'Your memberships and direct links to community channels.',
    NoMembershipTitle: 'No community membership found',
    NoMembershipMessage: 'Browse the Community Directory to find and join a community.',
    BrowseDirectoryLabel: 'Browse communities',
    MembershipUnavailableTitle: 'Membership status is not enabled',
    MembershipUnavailableMessage: 'Use the community links to request access while Graph approval is pending.',
    CharterTitle: 'Community charter',
    CharterSubtitle: 'Author the working model, complete launch readiness, and record three-way sign-off.',
    CommunityLabel: 'Community',
    InteractionModelLabel: 'Interaction model',
    CadenceLabel: 'Cadence and office hours',
    ReadinessPlanLabel: 'Readiness and certification plan',
    LaunchReadinessLabel: 'Launch readiness',
    CharterStatusLabel: 'Workflow status',
    CharterVersionLabel: 'Charter version',
    SignOffsLabel: 'Sign-offs',
    AuditLabel: 'Audit record',
    LeadSignOffLabel: 'Community Lead',
    ProgramManagerSignOffLabel: 'Program Manager overlap review',
    SMESignOffLabel: 'Subject Matter Expert',
    NotSignedLabel: 'Not signed',
    SaveDraftLabel: 'Save draft',
    SubmitReviewLabel: 'Submit for review',
    RequestChangesLabel: 'Request changes',
    SignLabel: 'Sign',
    SignedOffMessage: 'This charter is signed off and published. The record is read-only.',
    CharterSavedMessage: 'Charter saved.',
    HealthTitle: 'Community health',
    HealthSubtitle: 'Six governance measures compared with each community launch baseline.',
    PeriodLabel: 'Reporting period',
    CommunityFilterLabel: 'Community view',
    PortfolioLabel: 'Portfolio',
    BaselineLabel: 'Baseline',
    DeltaLabel: 'Change from baseline',
    NoMetricsLabel: 'No metric has been recorded for this period.',
    RetirementTitle: 'Forum retirement register',
    RetirementSubtitle: 'Track migration, merge, and closure of legacy forums and channels.',
    ProgressLabel: 'Forums completed',
    DispositionFilterLabel: 'Disposition',
    AllDispositionsLabel: 'All dispositions',
    AddForumLabel: 'Add forum',
    ForumNameLabel: 'Forum, distribution list, or channel',
    DispositionLabel: 'Disposition',
    TargetCommunityLabel: 'Target community',
    CompletionDateLabel: 'Completion date',
    StateLabel: 'State',
    CompletedLabel: 'Completed',
    PendingLabel: 'Pending',
    NoRetirementItemsLabel: 'No legacy forums are recorded.',
    PropertyPaneDescription: 'Configure this SSD Communities portal web part.',
    BasicGroupName: 'Portal settings',
    CommunityIdFieldLabel: 'Community item ID',
    DetailPageUrlFieldLabel: 'Community detail page URL',
    DirectoryPageUrlFieldLabel: 'Community directory page URL',
    MembershipEnabledFieldLabel: 'Enable Graph membership and join',
    ReadinessItemsFieldLabel: 'Six launch-readiness checks (one per line)'
  };
});